### ISSUE TITLE
?

### ISSUE THREAD

**Issue by FelipeRearden** [ryanjamurphy/workbench-obsidian#11]

**Comment by ryanjamurphy** [comment]
This is a good idea, and it shouldn't be too tricky. I'll try to add it into the next version!

**Comment by FelipeRearden** [comment]
> This is a good idea, and it shouldn't be too tricky. I'll try to add it into the next version!

Thanks for the reply Ryan!!! I'm glad you liked my suggestion. 

Thank you very much and have a great day!
- Felipe
