### ISSUE TITLE
Feature Request: Quickly change the title of the workbench

### ISSUE THREAD

**Issue by q7z** [ryanjamurphy/workbench-obsidian#2]
Is it possible to add a feature which allows you to quickly change the title of the workbench? Right now one must manually go to the plugin settings to do so each time

**Comment by ryanjamurphy** [comment]
Interesting. I'd previously considered it but held off on implementing it. What's the workflow you're hoping for? How do you imagine this working?

**Comment by q7z** [comment]
I'm not sure, but perhaps even something that maybe allows me to type a backlink on the first line [[000 Home]] and the plugin reads that file as the one to send the embed/copy to?

**Comment by ryanjamurphy** [comment]
Forgot to comment here—I'll think on this. The easiest thing is probably to do a "Switch workbench" command in which you can type the name of the new workbench and it'll adjust the target note.

The key problem is that autocomplete mechanisms aren't available in the API, so you'll have to make sure you get the note name exactly right. Maybe I can provide some kind of quick-switcher menu for favourite options in that same modal or something...

**Comment by ryanjamurphy** [comment]
This is now possible in 1.6.0 with the new `Change your Workbench` command in the command palette.
