### ISSUE TITLE
workbench link heading/section and embed heading/section does not work . 

### ISSUE THREAD

**Issue by nilarkian** [ryanjamurphy/workbench-obsidian#25]
did anything break as obsidian updated, the link block,line and everything works just the headings don't . nothing gets linked to the workbench

**Comment by pamela-drouin** [comment]
I'm having the same issue as well

**Comment by ryanjamurphy** [comment]
Thanks for the reports! Workbench and Obsidian's new click-to-open-tabs/panes functionality definitely conflict. I will have to think about how to design around it — open to ideas! 🙂

**Comment by ryanjamurphy** [comment]
Sorry, looks like I misunderstood this issue previously. I've just fixed it with release 1.6.3 (this report was reposted as #27).
