### ISSUE TITLE
【Bug report】embed current heading not working in obsidian 1.5.8

### ISSUE THREAD

**Issue by Ravenclawer** [ryanjamurphy/workbench-obsidian#27]
The embed current heading/Section to workbench note not working in the obsidian 1.5.8.

**Comment by ryanjamurphy** [comment]
Hm. Thanks for the report. 

Indeed, it looks like something broke with the logic used to find the section and create the link — this line:

https://github.com/ryanjamurphy/workbench-obsidian/blob/4403d6ae0ba1f9f7b298bd9f333a00a2594dc83c/main.ts#L492

I'm not likely to have time to look into it soon but it shouldn't be a difficult fix if anyone else wants to look into it!

**Comment by Ravenclawer** [comment]
Thank you for the fast reply. I‘m trying to fix it this entire morning. However, I don't know much about coding. So I failed. I have filed help information in the community forum and discord channels, hoping someone could help fix it. By the way, this is a great function, and for those who want to use a similar function. I have a clumsy workaround, using the Note Composer plugin, and you have to select the section you want to extract and the note you want to add the extracted text every time. 
Looking forward to the update of the workbench plugin, and thank you for creating it!

**Comment by Ravenclawer** [comment]
https://forum.obsidian.md/t/workbench-the-embed-current-section-heading-to-the-workbench-not-working-in-the-1-5-8-version-ofobsidian/79280?u=ocarinalover

**Comment by Ravenclawer** [comment]
![image](https://github.com/ryanjamurphy/workbench-obsidian/assets/73892411/3c75d470-dd3a-4ed3-b62e-3f824cb52425)
I thought it was the  Var currentline = editor.doc.sel.ranges[a].anchor.line;

**Comment by ryanjamurphy** [comment]
Good spelunking. You were right, ish. That method wasn't retrieving the line number anymore. 

The latest release (1.6.3) should fix the issue.

**Comment by Ravenclawer** [comment]
Thank you for the prompt fixation of the issue. It's now working like a charm.
