### ISSUE TITLE
insert line break before adding new note

### ISSUE THREAD

**Issue by mendelkranz** [ryanjamurphy/workbench-obsidian#3]
I'm probably just doing this wrong, but is there a way to insert a line break before the new note gets copied to the workbench? I tried fiddling with the prefix option in settings, but nothing seemed to do it. Thanks for a great plugin!

**Comment by ryanjamurphy** [comment]
Sorry, @mendelkranz, I think the initial versions included these blank lines and I removed them in 1.4.0. I've just added a toggle to include blank lines between entries. Update to 1.5.0 and you'll have the option!
