### ISSUE TITLE
How does Alt+Click work?

### ISSUE THREAD

**Issue by wenlzhang** [ryanjamurphy/workbench-obsidian#5]
I am using the latest version of Workbench with Obsidian 0.9.19. When I Alt+Click a note heading, nothing happens in the Workbench note. Am I using this the correct way?

**Comment by ryanjamurphy** [comment]
The click commands were designed to target only one line at a time.

Note the settings in the plugin's preferences—they do nothing by default (I didn't want to mess with a people's clicking without their opting in!) but you can change the two types of clicks to do a variety of things with the line you're clicking on.

Have you enabled one of those settings and, if so, are you still having issues?

I will address the headings idea in your second issue.

**Comment by wenlzhang** [comment]
My bad. I misunderstood the usage of Alt+Click. Alt+Click a note link like `[[Note]]` would successfully insert the note link to the Workbench note.

I was going to ask if it is possible to link the current note to the Workbench note by Alt+Click a heading of the current note or anywhere within the current note. According to your answer to the other issue, I think this can also be accomplished by using hotkeys.

**Comment by ryanjamurphy** [comment]
I think this can be closed, yeah? Let me know otherwise!
